### ISSUE TITLE
Document examples for passing labels and annotations to `HelmChart` values using template functions

### ISSUE THREAD

**Issue by cbodonnell** [replicatedhq/replicated-starter-helm#15]
**Problem:** Some vendors may want to allow end-users to add custom annotations, labels, nodeSelectors, and things of this nature to application resources to ensure compatibility with the environment.  This can be difficult to accomplish since it requires using replicated template functions within the `HelmChart` custom resource, which can be unwieldy and difficult to troubleshoot depending on what the vendor trying to accomplish.

**Solution:** The following is an example where a vendor can provide a textarea config option to allow an end-user to conditionally add additional annotations to their application resources:

Example config option to expose a textarea when a checkbox is selected:
```
    - name: set_additional_annotations
      title: Set Additional Annotations
      type: bool
    - name: additional_annotations
      title: Additional Annotations
      type: textarea
      when: repl{{ ConfigOptionEquals "set_additional_annotations" "1" }}
```

Usage in `HelmChart` custom resource `optionalValues` field so they are only included when the checkbox is selected.  The `nindent` template function will make sure the value is rendered on the appropriate line and with the right indentation:
```
apiVersion: kots.io/v1beta2
kind: HelmChart
...
  optionalValues:
  - when: 'repl{{ ConfigOptionEquals "set_additional_annotations" "1" }}'
    recursiveMerge: true
    values:
      commonAnnotations: repl{{ ConfigOption `additional_annotations` | nindent 8 }}
```
If the user selects the checkbox and pastes in some annotations, it will render as the following:
```
apiVersion: kots.io/v1beta2
kind: HelmChart
...
  optionalValues:
  - when: 'true'
    recursiveMerge: true
    values:
      commonAnnotations: 
        app: my-app
        example.com/allow-application: true
```

Since it is an optional value, they will only be merged in if the `when` condition evaluates to `"true"`.  This would be the resulting `values.yaml` used to install the chart:
```
commonAnnotations:
  app: my-app
  example.com/allow-application: true
```
